GT-176 Adjust Inverted Index changes
arangodb/go-driver pull request #433
Opened 2022-09-15 11:57 UTC by jwierzbo

2022-09-15 12:26 UTC, nikita-vanyasin approved these changes
Small comment about `searchField`

2022-09-15 12:26 UTC, nikita-vanyasin commented on collection_indexes.go
> +	SearchField bool `json:"search,omitempty"`
field name is `searchField` according to docs

2022-09-15 15:32 UTC, rashtao requested changes

2022-09-15 15:32 UTC, rashtao commented on view_arangosearch.go
>  	WriteBufferIdel *int64 `json:"writebufferIdle,omitempty"`
Shouldn't this be `WriteBufferIdle`?

2022-09-16 11:20 UTC, rashtao approved these changes

2022-09-16 11:26 UTC, merged