Fix tests for optimizeTopK property
arangodb/go-driver pull request #507
Opened 2023-05-17 13:19 UTC by informalict

2023-05-17 13:23 UTC, jwierzbo requested changes

2023-05-18 04:56 UTC, informalict commented on test/index_ensure_test.go
> +				if version.Version.CompareTo("3.11.0") >= 0 {
but we don't want to skip this test. We want to avoid checking some fields for 3.11 version

2023-05-18 10:43 UTC, informalict commented on test/index_ensure_test.go
> +				if version.Version.CompareTo("3.11.0") >= 0 {
done

2023-05-18 10:45 UTC, jwierzbo approved these changes

2023-05-18 11:47 UTC, merged